-------------------------------------------------------------------------------
Test set: cn.bytts.dao.UserDaoTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 92.726 s <<< FAILURE! - in cn.bytts.dao.UserDaoTest
updateUser(cn.bytts.dao.UserDaoTest)  Time elapsed: 30.528 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.updateUser(UserDaoTest.java:45)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.updateUser(UserDaoTest.java:45)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.updateUser(UserDaoTest.java:45)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.updateUser(UserDaoTest.java:45)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at cn.bytts.dao.UserDaoTest.updateUser(UserDaoTest.java:45)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

selectUserByTag(cn.bytts.dao.UserDaoTest)  Time elapsed: 0.015 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [D:\JavaPojects\CreateTime\target\classes\mybatis\mapper\UserDao.xml]
### The error may involve cn.bytts.dao.UserDao.selectUserByEmail
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.selectUserByTag(UserDaoTest.java:26)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [D:\JavaPojects\CreateTime\target\classes\mybatis\mapper\UserDao.xml]
### The error may involve cn.bytts.dao.UserDao.selectUserByEmail
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.selectUserByTag(UserDaoTest.java:26)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.selectUserByTag(UserDaoTest.java:26)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.selectUserByTag(UserDaoTest.java:26)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at cn.bytts.dao.UserDaoTest.selectUserByTag(UserDaoTest.java:26)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

insertUser(cn.bytts.dao.UserDaoTest)  Time elapsed: 30.317 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.insertUser(UserDaoTest.java:33)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.insertUser(UserDaoTest.java:33)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.insertUser(UserDaoTest.java:33)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.insertUser(UserDaoTest.java:33)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at cn.bytts.dao.UserDaoTest.insertUser(UserDaoTest.java:33)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

deleteUserByTag(cn.bytts.dao.UserDaoTest)  Time elapsed: 30.31 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.deleteUserByTag(UserDaoTest.java:39)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.deleteUserByTag(UserDaoTest.java:39)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.deleteUserByTag(UserDaoTest.java:39)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at cn.bytts.dao.UserDaoTest.deleteUserByTag(UserDaoTest.java:39)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at cn.bytts.dao.UserDaoTest.deleteUserByTag(UserDaoTest.java:39)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

